### ISSUE TITLE
Intermittent errors publishing HeartbeatEvent(s)

### ISSUE THREAD

**Issue by thinrichs** [NimbusAPI/Nimbus#192]
We intermittently received the following errors.  Most of the time they are related to HeartbeatEvents.  

They are timeouts trying to connect to ASB (I think?).  They're fairly intermittent, we get a couple a day, and the heartbeat runs every 30 seconds, right?  

So this will happen maybe 1 out of every 1000 publishes.  

It is also very spiky... hours with no issues, and then 3 - 6 of these in a 20 minute period, that kind of thing

We haven't really been able to pin down some type of cause.  In your experience(s) what is going to cause this?

Reformatted a little for readability:

```
Error "publishing" "HeartbeatEvent" (8538cc1c-0e29-45b1-a3af-148b3dfe14ce) to "t.nimbus.messagecontracts.controlmessages.heartbeatevent" 
(MessageMetadata { MessageId: 8538cc1c-0e29-45b1-a3af-148b3dfe14ce, CorrelationId: 8538cc1c-0e29-45b1-a3af-148b3dfe14ce, ShortMessageTypeName: "HeartbeatEvent", MessageType: "Nimbus.MessageContracts.ControlMessages.HeartbeatEvent" })
System.TimeoutException: The request operation did not complete within the allotted timeout of 00:01:10. The time allotted to this operation may have been a portion of a longer timeout.
```

If there is environment / system information that would help, just let me know

**Comment by thinrichs** [comment]
I've also realized once Nimbus is in this state the process Pegs a CPU core.  It seems there is some loop that it gets into?

**Comment by waheedsayed** [comment]
I saw similar events but I think this is due to Azure Service Bus availability itself.

In my solution, I have different installations, on-cloud & on-premises, and sometimes I can see this happening from different locations at the same moment. Hopefully, one of Nimbus team can confirm or dismiss this idea.

Because NimbusAPI is based on Azure SDK 2.1, at this time Service Bus didn't have a Retry logic and team didn't introduce any. I thought about introducing Polly to the codebase to handle retries but I'm not sure what are the team plans. Specially, if in future, NimbusAPI upgrades to a recent Azure SDK, a basic Retry logic will be available by default. Currently, I have only retries for sending my message types.

**Comment by DamianMac** [comment]
Hey guys

We're not upgrading the SDK because we want / need to support Windows Service Bus. If you'd like to lobby Microsoft to release an SDK that supports all their stuff we'll use it :)

@thinrichs what is going on with your app when it happens ? is it quiet ? Busy ? does it recover from CPU pegging ? What else can you tell us ?

**Comment by thinrichs** [comment]
Damian,

The app is quiet, even with no events / command going through the system,
the exe sits pegged, and never recovers.  It hasn't always done this so I'm
kind of at a loss.  It's on a Azure VM in the same region as the ASB
instance.

We did recently upgrade from 2.0.0.88 to 2.0.0.97 .  I don't remember
seeing the pegging on 2.0.0.88

I'm not sure the pegging is related to the ASB availability.  Recently
there was an ASB availability issue in US West, and thats when we looked
deeper into our production instance and saw the pegging.

But even after ASB came back to stasis, and restarting everything, it still
pegs.

CPU at 50% and nothing going on in the log, except for the performance
metrics heartbeat every 30 seconds.

I even tried to create a new Azure Service Bus instance and update my
config to it (so no commands / events are coming into the system except for
our custom heartbeats), and it still pegged.

I think my next steps will be to take out our three custom heartbeats (we
created them on when we were on Nimbus 1, before IHeartbeatEvent existed)
one at a time and see if I get anywhere with that.

That would be weird though, because we've had that code in prod for like 9
months

Damian thanks for the follow up.

Thanks,

Tommy Hinrichs

**Comment by waheedsayed** [comment]
@DamianMac  Hi Damian. 
I mainly talked about the Retry logic not about upgrading. I have also a scenario that includes on-premises Service Bus for Windows Server, so definitely I see what you mean.

I'll open another issue for this to ask for your feedback/plans for Retry & Transient Faults handling.

Thanks for responding to this.

**Comment by taliesins** [comment]
I think this is related #218
