### ISSUE TITLE
Subscribers Responsibilities / EventHandler Dependencies

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#230]
I'm working on a sample app where a customer places an order for coffee. The barista, makes the coffee and a cashier charges the customer, then the waiter delivers the order.

Ex:   Customer. Barista. Cashier. Waiter
```
Customer    -> OrderPlacedEvent.
Barista.MakeOrder<OrderPlacedEvent>
Cashier.ChargeCustomer<OrderPlacedEvent>
```

```
Barista  -> OrderReadyEvent
```

```
Cashier -> OrderPaidEvent
```

```
Waiter.DeliverOrder<OrderReadyEvent>
   if ( OrderPaid)
        ServeOrder
   else
       ???
```
 
So in this scenario if the OrderReadyEvent is received by the waiter before the OrderPaidEvent. 

1. Is the Waiter responsible for confirming that the OrderPaid.   
* If so, what do we do, does it wait? 
* Does Nimbus support a Retry? 
* How do I think about responsibility?  
* I see that NServiceBus has a concept of "Sagas" that supports this "Long Running" concept. Is there a Nimbus way?

**Comment by markalanevans** [comment]
Here is the "System" i'm working on.

![Mockup](https://www.evernote.com/l/AJGTc3Hi1EhPI7CO4q_epSSCzA7NgWtwFp8B/image.png)

**Comment by DamianMac** [comment]
1. Depends :) What would you do if it was your coffee shop ? Would you hand the coffee to the customer even if they hadn't finished the transaction? Or would you have the waiter hold the coffee until the cashier called out that it was OK?
2. See 1.
3. Yes, but not in the way that you're modelling in that diagram. It's a retry for failures.
4. Too big a question for github
5. No, it's not something we believe in. (There's a longer answer for that, but see point 4)

**Comment by lukeschafer** [comment]
Philosophical questions of sagas aside, what you think you want to achieve with a saga is probably achievable in different ways, but if the model fits the scenario, then 'sagas' aren't hard.

The only thing that a saga from nservicebus gives you is an abstraction over persisting the state machine. You can achieve that yourself quite easily, with very little ceremony other than locking (which may require cross process/machine locks, or at the DB level with read committed or similar) to ensure a consistent state. Even then, YMMV and that complexity may not be required.

Another option is to to use the LongRunning, and utilise multicast events to handle termination of the handler.

**Comment by IanYates** [comment]
The blog of @uglybugger has some good articles around some of this.  See http://www.uglybugger.org/software/post/brisbane_azure_user_group_talk_on_azure_service_bus_made_easy and http://www.uglybugger.org/software/post/support_for_long_running_handlers_in_nimbus for a start, plus others on there about Nimbus too

**Comment by markalanevans** [comment]
@IanYates  i did a quick search of the project, "ILongRunningHandler" doesn't pop up. Is it documented somewhere?

@lukeschafer @DamianMac perhaps i need to read a bit more to better understand how I should think about this, in the current scenario, the Waiter would check the DB for the order being paid. If not Paid, I don't want to block the next item from being delivered by the waiter if the next customer has Paid, but I also don't want a customer to wait for all the orders behind him to complete before he can get his coffee, assuming that the Payment clears just a few minutes later. 

What are my options? Does your LongRunningHandler allow for other items to be processed?

I'm going to watch that Video you posted. But if i'm thinking about this process wrong, i'd love a reference to read about how to think about this with what is available to me w/ Nimbus.

**Comment by uglybugger** [comment]
Hi @markalanevans :)  I'm chiming in a bit late here but it sounds like you actually have two events that could be a trigger for the waiter to serve the coffee to the customer: the OrderPaidForEvent and the OrderReadyEvent.

Let's pretend for a second that we have three roles rather than two and add the explicit concept of a Waiter. We can collapse this again in a minute but it should illustrate the point.

Our cashier is responsible for taking the order, adding it to the make line and taking payment. When payment is received, the Cashier publishes an OrderPaidForEvent.

Our Barista is responsible for making coffee. When an order is placed, the Barista commences making the coffee. When the coffee is ready, the Barista publishes an OrderReadyEvent.

Our Waiter is responsible for getting the coffee to the customer. When an OrderReadyEvent is observed, our Waiter checks if the order has been paid for. If so, s/he delivers it to the customer. If not, s/he ignores it. Likewise, when an OrderPaidForEvent is observed, the Waiter checks whether the order is ready. If the order is ready, s/he delivers it to the customer. If not, s/he ignores it.

Effectively what we have is two events that can feed into the same action taken by the Waiter. The "saga" state is actually derived from our domain model (or a read model projected from it).

This is pretty much what you'd teach a human waiter to do. "If you hear the 'Food's ready' bell ding, check if it's been paid for and give it to the customer if so. Likewise, once a customer has paid for their coffee, check if it's already been made and hand it to them."

What this tends to do is 1) model the system much more closely along the lines of human behaviours, and 2) flush out any weirdness in your business rules. For instance, is it sensible to start making an order before it's been paid for, or should the OrderPaidForEvent actually be a trigger for the Barista to start making the coffee?

Does that make sense?
