### ISSUE TITLE
Topic EntityPath and Listen permission

### ISSUE THREAD

**Issue by Timothyoverton** [NimbusAPI/Nimbus#246]
Hi Guys,

We have a basic nimbus topshelf service running on a client server, we are trying to setup the service to listen for service bus events on a specific topic. We have seen in the old azure portal that you can setup a connection string for a topic with listen only permission, is this compatible with the latest nimbus version? 
We are getting errors when including EntityPath in the connection string and we are also getting errors that manage permission is required. If it is possible to connect to topic with listen permission, can you please show how to configure the bus?

Many thanks,
Tim

**Comment by DamianMac** [comment]
Hi @Timothyoverton 
You need manage permission because we ensure the queues are all there when the bus spins up.

It sounds like a silly constraint I know, but because of a tedious quirk with Azure Service Bus it's much quicker and less flaky to try to create a queue rather than try to make sure it exists. 

I'm not opposed to a startup option that says "I trust everything is there", but we don't have one yet.

**Comment by Timothyoverton** [comment]
Ok, I've got my head around the permissions. Thanks.
